{
 "title": "Test Result",
 "description": "k6 Test Result",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "testid", "query": { "query": "label_values(testid)" } },
   { "name": "scenario", "query": { "query": "label_values(scenario)" } },
   { "name": "url", "query": { "query": "label_values(url)" } }
  ]
 },
 "panels": [
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Made",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(k6_http_reqs{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "targets": [
    {
     "expr": "max(k6_http_reqs{testid=~\"$testid\",expected_response=\"false\"}*k6_http_req_failed{testid=~\"$testid\",expected_response=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak RPS WIP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(irate(k6_http_reqs{testid=~\"$testid\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Response Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(k6_http_req_duration_p95{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_data_received{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_data_sent{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "k6_vus{testid=~\"$testid\"}",
     "legendFormat": "Active VUs"
    },
    {
     "expr": "avg(irate(k6_http_reqs{testid=~\"$testid\"}[1m]))",
     "legendFormat": "Requests Rate"
    },
    {
     "expr": "avg(rate(k6_http_reqs{testid=~\"$testid\", expected_response=\"false\"}[$__interval])*k6_http_req_failed{testid=~\"$testid\",expected_response=\"false\"})",
     "legendFormat": "Failed Requests Rate"
    },
    {
     "expr": "avg(k6_http_req_duration_avg{testid=~\"$testid\"})",
     "legendFormat": "Response  Time"
    }
   ]
  },
  {
   "title": "Iteration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_iterations{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data flow",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_received{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(k6_data_sent{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Error Code Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(error_code) (rate(k6_http_reqs{testid=~\"$testid\", expected_response=\"false\"}[$__interval])*k6_http_req_failed{testid=~\"$testid\",expected_response=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Iteration WIP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_dropped_iterations{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checks WIP",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "k6_checks{testid=~\"$testid\"}"
    }
   ]
  },
  {
   "title": "Thresholds WIP",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "k6_http_reqs{testid=~\"$testid\"}"
    },
    {
     "expr": "k6_http_req_duration_min{testid=~\"$testid\"}"
    },
    {
     "expr": "k6_http_req_duration_avg{testid=~\"$testid\"}"
    },
    {
     "expr": "k6_http_req_duration_p95{testid=~\"$testid\"}"
    },
    {
     "expr": "k6_http_req_duration_max{testid=~\"$testid\"}"
    }
   ]
  },
  {
   "title": "HTTP breakdown",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(k6_http_req_blocked_avg{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"})",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum(k6_http_req_connecting_avg{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"})",
     "legendFormat": "Connecting"
    },
    {
     "expr": "sum(k6_http_req_duration_avg{testid=~\"$testid\",url=~\"$url\",scenario=~\"$scenario\"})",
     "legendFormat": "Duration"
    },
    {
     "expr": "sum(k6_http_req_receiving_avg{testid=~\"$testid\",url=~\"$url\",scenario=~\"$scenario\"})",
     "legendFormat": "Receiving"
    },
    {
     "expr": "sum(k6_http_req_sending_avg{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"})",
     "legendFormat": "Sending"
    },
    {
     "expr": "sum(k6_http_req_tls_handshaking_avg{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"})",
     "legendFormat": "TLS Handshaking"
    },
    {
     "expr": "sum(k6_http_req_waiting_avg{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Scenarios",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "avg by(scenario) (k6_http_req_duration_p95{testid=~\"$testid\",scenario=~\"$scenario\", expected_response=\"true\"})"
    },
    {
     "expr": "sum by(scenario) (max(k6_http_reqs{testid=~\"$testid\", scenario=~\"$scenario\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(scenario) (rate(k6_http_reqs{testid=~\"$testid\",scenario=~\"$scenario\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(scenario) (k6_iterations{testid=~\"$testid\",scenario=~\"$scenario\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(scenario) ( k6_http_reqs{testid=~\"$testid\", scenario=~\"$scenario\",expected_response=\"false\"}*k6_http_req_failed{testid=~\"$testid\", scenario=~\"$scenario\",expected_response=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scenario level metrics $scenario",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "repeat": "scenario",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scenario $scenario",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "avg by(scenario) (k6_http_req_duration_p95{testid=~\"$testid\",scenario=~\"$scenario\", expected_response=\"true\"})"
      },
      {
       "expr": "sum by(scenario) (max(k6_http_reqs{testid=~\"$testid\", scenario=~\"$scenario\"}))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(scenario) (rate(k6_http_reqs{testid=~\"$testid\",scenario=~\"$scenario\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(scenario) (k6_iterations{testid=~\"$testid\",scenario=~\"$scenario\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(scenario) ( k6_http_reqs{testid=~\"$testid\", scenario=~\"$scenario\",expected_response=\"false\"}*k6_http_req_failed{testid=~\"$testid\", scenario=~\"$scenario\",expected_response=\"false\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "k6_vus{testid=~\"$testid\"}",
       "legendFormat": "Active VUs"
      },
      {
       "expr": "avg(irate(k6_http_reqs{testid=~\"$testid\",scenario=~\"$scenario\"}[1m]))",
       "legendFormat": "Requests Rate"
      },
      {
       "expr": "avg(rate(k6_http_reqs{testid=~\"$testid\", expected_response=\"false\",scenario=~\"$scenario\"}[$__interval])*k6_http_req_failed{testid=~\"$testid\",expected_response=\"false\",scenario=~\"$scenario\"})",
       "legendFormat": "Failed Requests Rate"
      },
      {
       "expr": "avg(k6_http_req_duration_avg{testid=~\"$testid\",scenario=~\"$scenario\"})",
       "legendFormat": "Response  Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Example Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Counter",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "k6_my_counter{testid=~\"$testid\"}"
      }
     ]
    },
    {
     "title": "gouge",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "expr": "k6_my_gauge{testid=~\"$testid\"}"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(k6_my_rate{testid=~\"$testid\"})"
      }
     ]
    },
    {
     "title": "trends",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "k6_my_trend_avg{testid=~\"$testid\"}",
       "legendFormat": "avg"
      },
      {
       "expr": "k6_my_trend_max{testid=~\"$testid\"}",
       "legendFormat": "max"
      },
      {
       "expr": "k6_my_trend_med{testid=~\"$testid\"}",
       "legendFormat": "med"
      },
      {
       "expr": "k6_my_trend_min{testid=~\"$testid\"}",
       "legendFormat": "min"
      },
      {
       "expr": "k6_my_trend_p90{testid=~\"$testid\"}",
       "legendFormat": "p90"
      },
      {
       "expr": "k6_my_trend_p95{testid=~\"$testid\"}",
       "legendFormat": "p95"
      }
     ]
    }
   ]
  }
 ]
}