# This is a basic workflow to help you get started with Actions

name: k6 Cloud Load Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "k6_load_test"
  k6_load_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Run Test
        uses: grafana/k6-action@v0.2.0
        with:
          cloud: true
          filename: main.js
          flags: -v -q # verbose, quiet
          token: ${{ secrets.K6_CLOUD_TOKEN }}
        env:
          K6_CLOUD_PROJECT_ID: 3526246
